{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "energy-optimizer.fullname" . }}
  labels:
    {{- include "energy-optimizer.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "energy-optimizer.fullname" . }}
  labels:
    {{- include "energy-optimizer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "energy-optimizer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "energy-optimizer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
