
services:
  energy-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: energy-optimizer:latest
    container_name: energy-optimizer
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=DEBUG
      - PROMETHEUS_URL=http://prometheus:9090
      - DRY_RUN=true
      - KUBECONFIG=/app/kubeconfig
    volumes:
      - ./models:/models
      - ./config:/config
      - ./data:/data
      - ${HOME}/.kube/config:/app/kubeconfig:ro
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
