global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'energy-optimizer'
    static_configs:
      - targets: ['energy-optimizer:8080']
    metrics_path: '/metrics'
